<div class="faq" data-bind="scope: 'faq-extension-item-alias'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "faq-extension-item-alias": {
                    "component": "MW_EasyFaq/js/faq/item"
                }
            }
        }
    }
}
</script>